enum ErrorEnum {
  // 400
  BAD_REQUEST = "BAD_REQUEST",
  SAME_DATE_MEASUREMENT = "SAME_DATE_MEASUREMENT",
  // 404
  MEASUREMENT_NOT_FOUND = "MEASUREMENT_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  // 500
  SERVER_ERROR = "SERVER_ERROR",
}

export { ErrorEnum };
